### ISSUE TITLE
[Feature request] Add "Restart in 60 seconds" dialog.

### ISSUE THREAD

**Issue by antsif-a** [UbayGD/reboottouefi#4]
Sometimes you accidentally click to this button and system just restarts to UEFI. I suggest adding confirmation dialog as it is when you're restarting normally via built-in button, with 60-seconds timer.

**Comment by UbayGD** [comment]
I think it is an interesting idea 🤔. I will see what I can do

**Comment by UbayGD** [comment]
I think I have more or less been able to replicate the restart dialog. I have not been able (or rather I have not known how) to reuse the existing one so I have created it from scratch.

This is the commit https://github.com/UbayGD/reboottouefi/commit/08367866b411ad5047ad19bb420ed852f9d718ca. I'm going to do some more tests before merge it in main and update the extension.

Once it is done I will close the issue.
