### ISSUE TITLE
Can you test it (gnome 43)

### ISSUE THREAD

**Issue by ghost** [UbayGD/reboottouefi#5]
Hello do you think it's possible to test it (and enable support) for gnome 43 beta (fedora user will need it soon)).

**Comment by UbayGD** [comment]
Hi! I'm already working on it but I'm not going as fast as I would like. I'm using my old ThinkPad x220 and a virtual machine with Fedora 37 beta.

My idea is to have it ready in time for the release.

**Comment by ghost** [comment]
> Hi! I'm already working on it but I'm not going as fast as I would like. I'm using my old ThinkPad x220 and a virtual machine with Fedora 37 beta.
> 
> My idea is to have it ready in time for the release.

Thanks !, because you extension is the only one totally mandatory for me :)
Hope to see gnome dev add this feature directly in gnome settings one day.

**Comment by UbayGD** [comment]
I already have something working in Gnome 43. I have to do some more tests but it seems to be ok.

https://github.com/UbayGD/reboottouefi/tree/dev

I hope to merge it soon.

**Comment by UbayGD** [comment]
Hi! I will close this issue. Gnome 43 support it's merged now on main branch.

**Comment by ghost** [comment]
> Hi! I will close this issue. Gnome 43 support it's merged now on main branch.

Thanks a Lot !!
