### ISSUE TITLE
Weird spaces before text

### ISSUE THREAD

**Issue by adamvalt** [UbayGD/reboottouefi#8]
![Screenshot from 2022-12-29 08-57-20(1)](https://user-images.githubusercontent.com/67600061/209922033-d4530113-348c-47d8-9180-607c46c63541.png)

Gnome version 43.2
Saw your comment in the code, maybe they fixed it? 
Or it is just colliding with some other extension.

**Comment by UbayGD** [comment]
Hi! I'm testing right now on Fedora 37 with Gnome 43.2 and it works fine.
What distro are you using? To test in a virtual machine and see if the same thing happens.

I'm seeing that you also get "hibernate" options. Are they of a another extension?

**Comment by maeries** [comment]
Same issue here. Manjaro with Gnome 43.2
![grafik](https://user-images.githubusercontent.com/30597531/210084483-4e8b8ad5-bb8d-4a4a-affa-99a00e897105.png)

**Comment by UbayGD** [comment]
Ok, I have created a VM with Manjaro and, indeed, the text appears with those extra spaces.

I will investigate why there is that difference between distros, since the Gnome version is the same. I will keep you informed.

**Comment by adamvalt** [comment]
Yes, manjaro. Thank you.

**Comment by LucasLelievre** [comment]
Hello, I have the same issue on Fedora 37 with Gnome 43.2.
I am able to fix it by changing `PopupMenu.PopupImageMenuItem(itemLabel, '')` by `PopupMenu.PopupMenuItem(itemLabel)` in the code (see the "Restart to Windows..." menu item I created).

![Screenshot from 2023-01-21 11-44-25](https://user-images.githubusercontent.com/32330783/213863575-540c0a1b-59f6-482e-9a13-cc1bb1f5f845.png)

What do you think ?

**Comment by UbayGD** [comment]
> Hello, I have the same issue on Fedora 37 with Gnome 43.2. I am able to fix it by changing `PopupMenu.PopupImageMenuItem(itemLabel, '')` by `PopupMenu.PopupMenuItem(itemLabel)` in the code (see the "Restart to Windows..." menu item I created).
> 
> ![Screenshot from 2023-01-21 11-44-25](https://user-images.githubusercontent.com/32330783/213863575-540c0a1b-59f6-482e-9a13-cc1bb1f5f845.png)
> 
> What do you think ?

It looks really good. I would never have thought to check if I was using the wrong MenuItem hahaha.

If you want you can make a pull request with that change.

**Comment by LucasLelievre** [comment]
> If you want you can make a pull request with that change.

I will then thank you.

**Comment by UbayGD** [comment]
A new extension update is on the way. If you have installed it from Gnome Extensions you should get the notification at some point.

I will close the issue as it should be all fixed. Thanks to all of you!
